-- MySQL Script generated by MySQL Workbench
-- Sun May 26 22:14:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurantegrupo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `restaurantegrupo` ;

-- -----------------------------------------------------
-- Schema restaurantegrupo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantegrupo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurantegrupo` ;

-- -----------------------------------------------------
-- Table `restaurantegrupo`.`catalogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`catalogo` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`catalogo` (
  `idCatalogo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id_estado de la cuenta',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Estado de la cuenta',
  PRIMARY KEY (`idCatalogo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`catalogoprod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`catalogoprod` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`catalogoprod` (
  `idCatalogoProd` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id}-estado_producto',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT 'nombre del estado',
  PRIMARY KEY (`idCatalogoProd`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`catalogotip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`catalogotip` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`catalogotip` (
  `idCatalogoProd` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id Categoria producto',
  `Nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT 'nombre de la categoria',
  PRIMARY KEY (`idCatalogoProd`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`meseros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`meseros` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`meseros` (
  `idMeseros` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id del meser',
  `Sexo` VARCHAR(1) NOT NULL COMMENT 'genero del mesero',
  `Nombre` VARCHAR(45) NOT NULL COMMENT 'nombre completo',
  `NCuenta` INT(11) NULL DEFAULT NULL COMMENT 'numero de cuenta',
  PRIMARY KEY (`idMeseros`),
  UNIQUE INDEX `idMeseros_UNIQUE` (`idMeseros` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 116
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`cuenta` (
  `idCuenta` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id de la cuenta',
  `Estado` INT(11) NOT NULL COMMENT 'estado de la cuenta',
  `NMesa` INT(11) NOT NULL COMMENT 'Numero de mesas',
  `FFin` DATETIME NULL DEFAULT NULL COMMENT 'Fecha dinalizacion',
  `FInicio` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de inicio cuenta',
  `Total` DECIMAL(10,0) NOT NULL COMMENT 'total de la cuenya',
  `Propina` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'propina ',
  `NMesero` INT(11) NULL DEFAULT NULL COMMENT 'Identificador del mesero',
  PRIMARY KEY (`idCuenta`),
  INDEX `NMesero_idx` (`NMesero` ASC) VISIBLE,
  INDEX `fkCatalogo_idx` (`Estado` ASC) VISIBLE,
  CONSTRAINT `fkCatalogo`
    FOREIGN KEY (`Estado`)
    REFERENCES `restaurantegrupo`.`catalogo` (`idCatalogo`),
  CONSTRAINT `fkMesero`
    FOREIGN KEY (`NMesero`)
    REFERENCES `restaurantegrupo`.`meseros` (`idMeseros`))
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`orden` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`orden` (
  `idOrden` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'identificador de la orden',
  `Cantidad` INT(11) NULL DEFAULT NULL COMMENT 'cantidad de productos',
  `Notas` VARCHAR(45) NULL DEFAULT NULL COMMENT 'notas sobre la orden',
  `Ncuenta` INT(11) NULL DEFAULT NULL COMMENT 'FK cunta a la que pertence',
  PRIMARY KEY (`idOrden`),
  INDEX `fkCuenta_idx` (`Ncuenta` ASC) VISIBLE,
  CONSTRAINT `fkCuenta`
    FOREIGN KEY (`Ncuenta`)
    REFERENCES `restaurantegrupo`.`cuenta` (`idCuenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`productos` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`productos` (
  `idProductos` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Tipo` INT(11) NULL DEFAULT NULL,
  `Precio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fktipo_idx` (`Tipo` ASC) VISIBLE,
  CONSTRAINT `fktipo`
    FOREIGN KEY (`Tipo`)
    REFERENCES `restaurantegrupo`.`catalogotip` (`idCatalogoProd`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurantegrupo`.`ord_prod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantegrupo`.`ord_prod` ;

CREATE TABLE IF NOT EXISTS `restaurantegrupo`.`ord_prod` (
  `idOrd_Prod` INT(11) NOT NULL COMMENT 'id_relacion:orden',
  `Norden` INT(11) NULL DEFAULT NULL COMMENT 'FK orden',
  `Tproducto` INT(11) NULL DEFAULT NULL COMMENT 'Tipo de producto',
  `Estado` INT(11) NULL DEFAULT NULL COMMENT 'Estado del producto',
  `PrecioVenta` DECIMAL(10,0) NULL DEFAULT NULL COMMENT 'precio momento de venta',
  PRIMARY KEY (`idOrd_Prod`),
  INDEX `fkorden_idx` (`Norden` ASC) VISIBLE,
  INDEX `fkproductos_idx` (`Tproducto` ASC) VISIBLE,
  INDEX `fkestado_idx` (`Estado` ASC) VISIBLE,
  CONSTRAINT `fkestado`
    FOREIGN KEY (`Estado`)
    REFERENCES `restaurantegrupo`.`catalogoprod` (`idCatalogoProd`),
  CONSTRAINT `fkorden`
    FOREIGN KEY (`Norden`)
    REFERENCES `restaurantegrupo`.`orden` (`idOrden`),
  CONSTRAINT `fkproductos`
    FOREIGN KEY (`Tproducto`)
    REFERENCES `restaurantegrupo`.`productos` (`idProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
